import{world}from "@minecraft/server";
import{ActionFormData,ModalFormData}from "@minecraft/server-ui";
import{jobs}from "./jobs.js";
import{getVillageInfo,countWorkers,ensureVillageOrigin,buildVillage,getBuiltLevel,getWorkLocation}from "./village.js";
import{getStorage,collectStorage,storageSummary}from "./storage.js";
import "./work.js";
import "./movement.js";

function rename(v,n){const j=jobs[String(v.getDynamicProperty("villagers_plus:job")??"")];v.setDynamicProperty("villagers_plus:name",n);v.nameTag="§a"+n+" §7| §f"+(j?.name??"Trabalhador")+" §7• §e"+Number(v.getDynamicProperty("villagers_plus:xp")??0)+" XP"}
function create(p,id){const j=jobs[id],o=ensureVillageOrigin(p);const v=p.dimension.spawnEntity("minecraft:villager_v2",{x:o.x+2,y:o.y+1,z:o.z+2});v.addTag("villagers_plus");v.setDynamicProperty("villagers_plus:job",id);v.setDynamicProperty("villagers_plus:owner",p.id);v.setDynamicProperty("villagers_plus:xp",0);v.setDynamicProperty("villagers_plus:state","working");v.setDynamicProperty("villagers_plus:name","Aldeão");v.setDynamicProperty("villagers_plus:home_x",o.x+2);v.setDynamicProperty("villagers_plus:home_y",o.y+1);v.setDynamicProperty("villagers_plus:home_z",o.z+2);rename(v,"Aldeão");buildVillage(p,getVillageInfo(p).level);p.sendMessage("§a"+j.icon+" "+j.name+" contratado! §7Ele vai trabalhar na vila e entregar a produção.");}
function jobMenu(p){const info=getVillageInfo(p),ids=Object.keys(jobs).filter(id=>(jobs[id].requiredLevel??1)<=info.level);const f=new ActionFormData().title("Contratar trabalhador").body("Nível da vila: "+info.level+" — "+info.name+"\nProfissões disponíveis:");for(const id of ids)f.button(jobs[id].icon+" "+jobs[id].name+"\n§7Nível "+(jobs[id].requiredLevel??1));f.show(p).then(r=>{if(!r.canceled&&r.selection!==undefined)create(p,ids[r.selection])})}
function nearbyWorkers(p){return p.dimension.getEntities({location:p.location,maxDistance:96,tags:["villagers_plus"]}).filter(v=>String(v.getDynamicProperty("villagers_plus:owner")??"")===p.id)}
function nameMenu(p){const list=nearbyWorkers(p);const v=list[0];if(!v){p.sendMessage("§cNenhum trabalhador seu está próximo.");return}new ModalFormData().title("Nomear trabalhador").textField("Nome","Ex.: João","Aldeão").show(p).then(r=>{if(!r.canceled)rename(v,String(r.formValues?.[0]??"Aldeão").trim().slice(0,24)||"Aldeão")})}
function storageMenu(p){const list=nearbyWorkers(p);if(!list.length){p.sendMessage("§cNenhum trabalhador seu está próximo.");return}const f=new ActionFormData().title("📦 Estoque dos trabalhadores").body("Escolha um trabalhador para ver e recolher o estoque.");for(const v of list.slice(0,20)){const n=String(v.getDynamicProperty("villagers_plus:name")??"Aldeão");f.button("📦 "+n+"\n"+storageSummary(v).slice(0,80));}f.show(p).then(r=>{if(r.canceled||r.selection===undefined)return;const v=list[r.selection];const before=storageSummary(v);const moved=collectStorage(v,p);p.sendMessage(moved>0?"§aVocê recolheu "+moved+" item(ns) do estoque.":"§eNão foi possível recolher itens agora.");p.sendMessage("§7Estoque restante: "+storageSummary(v));})}
function villageMenu(p){const i=getVillageInfo(p),w=countWorkers(p),built=getBuiltLevel(p);const next=i.next?(i.next.name+" ("+i.next.xp+" XP)"):"Nível máximo";const f=new ActionFormData().title("🏘️ Evolução da Vila").body("Nível "+i.level+" — "+i.name+"\nXP: "+i.xp+"\nPróximo: "+next+"\nDesbloqueio: "+i.unlock+"\nTrabalhadores: "+w+"\nConstruído até: nível "+built);f.button("🏗️ Construir/atualizar vila");f.button("📦 Estoque dos trabalhadores");f.button("👷 Contratar trabalhador");f.button("Fechar");f.show(p).then(r=>{if(r.canceled)return;if(r.selection===0){buildVillage(p,i.level)}if(r.selection===1)storageMenu(p);if(r.selection===2)jobMenu(p)})}
world.afterEvents.itemUse.subscribe(e=>{if(e.itemStack?.typeId!=="minecraft:compass")return;const p=e.source;ensureVillageOrigin(p);const f=new ActionFormData().title("Villagers+ V5").body("Sua vila agora constrói prédios, desbloqueia profissões e gerencia estoques.");f.button("👷 Contratar trabalhador");f.button("✏️ Dar nome");f.button("🏘️ Evolução e construções");f.button("📦 Recolher estoque");f.show(p).then(r=>{if(r.canceled)return;if(r.selection===0)jobMenu(p);if(r.selection===1)nameMenu(p);if(r.selection===2)villageMenu(p);if(r.selection===3)storageMenu(p)})});